### PR TITLE
[Ready to merge] "Complete PR" to restore split method

### PR DESCRIPTION
**Pull request by wiibaa**
- bugfix from #79 
- added tests
- added CHANGELOG + version bump

Replace PR #79 
Fixed bugs: #78 and elastic/logstash#5678

### CODE REVIEW

**Comment by wiibaa** [comment]
@suyograo @ph can you confirm such PR are best for the core team to review/merge/publish in one-go atm

**Comment by suyograo** [comment]
LGTM

**Comment by suyograo** [comment]
@wiibaa you can merge it as well :)

**Comment by ph** [comment]
good job @wiibaa !

**Pull request merged**
