### PR TITLE
Add array_remove_duplicate.

### PR DESCRIPTION
**Pull request by adamjt**
This PR addresses comments at:

https://github.com/logstash-plugins/logstash-filter-unique/issues/1

### CODE REVIEW

**Comment by jordansissel** [comment]
Code looks good. 

Docs: Can you also add docs to `docs/index.asciidoc` for this new setting?

**Comment by jordansissel** [comment]
Also looks like there's a git conflict that needs resolving.

**Comment by shoito** [comment]
@adamjt I hope this to be merged🙏

**Comment by adamjt** [comment]
@shoito Whoops, I'll fix this up this week!

**Comment by adamjt** [comment]
@jordansissel @shoito I've updated the merge conflict and asciidoc - Travis is failing on something seemingly unrelated. `invalid level[OFF] for logger[]`

**Comment by ekho** [comment]
@adamjt could you push something to PR to trigger travis build? Issue with invalid level fixed at https://github.com/elastic/logstash/issues/8518

**Comment by adamjt** [comment]
@ekho All set, thanks!

**Comment by ekho** [comment]
@jordansissel all problems has been fixed. Could you merge PR ?

**Comment by jordansissel** [comment]
In future PRs, please disable your editor's "trim whitespace" feature as it makes the diff very noisy and hard to review.

**Comment by jordansissel** [comment]
Ahh, turns out we already have a filter to do this feature: https://github.com/logstash-plugins/logstash-filter-unique.

Let's use that filter instead.

**Comment by adamjt** [comment]
@jordansissel This PR was opened based off of https://github.com/logstash-plugins/logstash-filter-unique/issues/1

**Comment by ekho** [comment]
@jordansissel to use logstash-filter-unique my pr https://github.com/logstash-plugins/logstash-filter-unique/pull/2 should be merged.

**Comment by andrewvc** [comment]
@ekho apologies for the delay, we've just published a gem with your patch to the unique filter! Thanks for all the great work :) I'm going to close this PR as a result.

**Pull request closed without merging**
